export type Primitive = 'any'
  | 'unknown'
  | 'object'
  | 'void'
  | 'never'
  | 'string'
  | 'number'
  | 'bigint'
  | 'boolean'
  | 'undefined'
  | 'null'
  | 'symbol'
export type IndexSignatureParameterType = 'symbol'|'string'|'number'
